name: Build Docs PDFs

on:
  pull_request:
    paths:
      - "docs/**.md"
      - "docs/theme.css"
      - ".github/workflows/build-docs.yml"
  push:
    branches: [ main ]
    paths:
      - "docs/**.md"
      - "docs/theme.css"
      - ".github/workflows/build-docs.yml"

jobs:
  build-pdfs:
    name: md_to_pdf
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Decide files to convert (changed on PR, all on push)
        id: files
        shell: bash
        run: |
          set -e
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base="${{ github.event.pull_request.base.sha }}"
            head="${{ github.event.pull_request.head.sha }}"
            CHANGED=$(git diff --name-only "$base" "$head" -- 'docs/*.md' | tr '\n' ' ')
          else
            CHANGED=$(ls docs/*.md 2>/dev/null || true)
          fi
          echo "changed_md=$CHANGED" >> "$GITHUB_OUTPUT"
          echo "Changed MD: $CHANGED"

      - name: Build PDFs
        if: steps.files.outputs.changed_md != ''
        run: |
          mkdir -p build-pdfs
          for f in ${{ steps.files.outputs.changed_md }}; do
            out="build-pdfs/$(basename "${f%.md}").pdf"
            echo "Converting $f -> $out"
            pandoc "$f" -o "$out" \
              --pdf-engine=wkhtmltopdf \
              --css=docs/theme.css \
              --toc --toc-depth=3 \
              --metadata title="$(basename "${f%.md}")"
          done

      - name: Upload PDFs (artifact for PRs)
        if: steps.files.outputs.changed_md != ''
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdfs
          path: build-pdfs/*.pdf

  commit-to-docs:
    # On push to main, write PDFs into docs/ and commit them
    needs: build-pdfs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Build ALL PDFs to docs/
        run: |
          shopt -s nullglob
          for f in docs/*.md; do
            out="docs/$(basename "${f%.md}").pdf"
            echo "Converting $f -> $out"
            pandoc "$f" -o "$out" \
              --pdf-engine=wkhtmltopdf \
              --css=docs/theme.css \
              --toc --toc-depth=3 \
              --metadata title="$(basename "${f%.md}")"
          done

      - name: Commit PDFs back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-build PDFs from Markdown"
file_pattern: docs/*.pdf
