name: Build Docs PDFs
on:
  push:
    branches: [ "main" ]
    paths:
      - "docs/**.md"
      - ".github/workflows/docs-to-pdf.yml"
jobs:
  md_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf
      - name: Convert Markdown to PDF
        run: |
          shopt -s nullglob
          for f in docs/*.md; do
            out="docs/$(basename "${f%.md}").pdf"
            echo "Converting $f -> $out"
            pandoc "$f" -o "$out" \
              --pdf-engine=wkhtmltopdf \
              --css=docs/theme.css \
              --metadata title="$(basename "${f%.md}")" \
              --toc --toc-depth=3
          done
      - name: Upload PDFs as artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdfs
          path: docs/*.pdf
