name: Build Docs PDFs
on:
  push:
    branches: ['main']
    paths:
      - 'docs/**.md'
      - 'docs/theme.css'
      - '.github/workflows/docs-to-pdf.yml'

jobs:
  md_to_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow committing back to the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc & wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert Markdown to PDF
        run: |
          shopt -s nullglob
          for f in docs/*.md; do
            out="docs/$(basename "${f%.md}").pdf"
            echo "Converting $f -> $out"
            pandoc "$f" -o "$out" \
              --pdf-engine=wkhtmltopdf \
              --css=docs/theme.css \
              --metadata title="$(basename "${f%.md}")" \
              --toc --toc-depth=3
          done

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: auto-build PDFs from Markdown'
          file_pattern: docs/*.pdf
